name = "Learning"
version = "0.1.0"
defaultTargets = ["Learning"]
lintDriver = "batteries/runLinter"
testDriver = "learning_test"

[[lean_lib]]
name = "Learning"
globs = ["Learning", "Learning.+"]

[[lean_lib]]
name = "Test"

[[lean_exe]]
name = "learning"
root = "Learning"

[[lean_exe]]
name = "learning_test"
root = "Test"

[[require]]
scope = "leanprover"
name = "doc-gen4"
rev = "v4.31.0"      # match toolchain

[[require]]
name = "batteries"
scope = "leanprover-community"
rev = "v4.31.0"                # match toolchain

[[require]]
name = "plausible"
scope = "leanprover-community"
rev = "v4.31.0"                # match toolchain
